version: '3.7'

services:
    currency-exchange:
       image: bettasplendens/microservices-currency-exchange-microservice:0.0.1-SNAPSHOT
       mem_limit: 700m
       ports:
        - "8000:8000"
       networks:
        - currency-network
       depends_on:
        - naming-server
        - rabbitmq
       environment:
        eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
        spring.zipkin.base-url: http://zipkin-server:9411/
        spring.rabbitmq.host: rabbitmq
        spring.zipkin.sender.type: rabbit
        spring.rabbitmq.port: 5672
        spring.rabbitmq.username: guest
        spring.rabbitmq.password: guest
    
    currency-conversion:
       image: bettasplendens/microservices-currency-conversion-service:0.0.1-SNAPSHOT
       mem_limit: 700m
       ports:
        - "8100:8100"
       networks:
        - currency-network
       depends_on:
        - naming-server
        - rabbitmq
       environment:
        eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
        spring.zipkin.base-url: http://zipkin-server:9411/
        spring.rabbitmq.host: rabbitmq
        spring.zipkin.sender.type: rabbit
        spring.rabbitmq.port: 5672
        spring.rabbitmq.username: guest
        spring.rabbitmq.password: guest

    api-gateway:
       image: bettasplendens/microservices-api-gateway:0.0.1-SNAPSHOT
       mem_limit: 700m
       ports:
        - "8765:8765"
       networks:
        - currency-network
       depends_on:
        - naming-server
        - rabbitmq
       environment:
        eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
        spring.zipkin.base-url: http://zipkin-server:9411/
        spring.rabbitmq.host: rabbitmq
        spring.zipkin.sender.type: rabbit
        spring.rabbitmq.port: 5672
        spring.rabbitmq.username: guest
        spring.rabbitmq.password: guest

    naming-server:
        image: bettasplendens/microservices-naming-server:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
         - "8761:8761"
        networks:
         - currency-network

    zipkin-server:
        image: openzipkin/zipkin:2.23
        mem_limit: 300m
        ports:
         - "9411:9411"
        networks:
         - currency-network
        environment:
         RABBIT_URI: amqp://guest:guest@rabbitmq:5672
        depends_on:
         - rabbitmq
        restart: on-failure
           

    rabbitmq:
        image: rabbitmq:3.8.12-management
        mem_limit: 300m
        ports:
         - "5672:5672"
         - "15672:15672"
        networks:
         - currency-network

networks: 
    currency-network: 